environment:
  matrix:
    - node_version: "6"
    - node_version: "4"

branches:
  only:
  - master
  - /.*-stable/

install:
  - ps: Install-Product node $env:node_version
  - yarn install

build_script:
  - ps: if ($env:APPVEYOR_REPO_BRANCH -eq 'master') { node ./scripts/set-dev-version.js }
  - npm run build
  - ps: ./scripts/build-dist.ps1
  - npm run build-win-installer

test_script:
  - npm run test-only

artifacts:
  - path: artifacts/*.msi
    name: Installer

cache:
 - node_modules
 - "%LOCALAPPDATA%/Yarn"

notifications:
  - provider: Webhook
    url: https://nightly.yarnpkg.com/archive_appveyor
    method: POST
    headers:
      Authorization:
        secure: uH4c9HNDdRuL4omqqbTtBq3KgzjGTFmpvPdiNuk9391Z0YXRoRLA1Ptpa3seZ0Pt
    on_build_failure: false
