environment:
  matrix:
    - node_version: "6"
    - node_version: "4"

branches:
  only:
  - master
  - /.*-stable/

install:
  - ps: Install-Product node $env:node_version
  - choco install -i yarn
  - refreshenv
  - yarn install

build_script:
  - ps: if ($env:APPVEYOR_REPO_BRANCH -eq 'master') { node ./scripts/set-dev-version.js }
  - npm run build
  - ps: ./scripts/build-dist.ps1
  - npm run build-win-installer

test_script:
  - npm run test-only

artifacts:
  - path: artifacts/*.msi
    name: Installer

cache:
 - node_modules
 - "%LOCALAPPDATA%/Yarn"
